<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <div class="container">
        <div class="row shadow-md bg-dark">
            <a href="/admin/products" class='btn  btn-primary float-right col'><?php echo $locale->_('products') ?></a>
            <a href="/admin/products/add" class='btn btn-success ms-3 float-right col'><?php echo $locale->_('add') . " " . $locale->_('product') ?></a>
            <a href="/logout" class='btn btn-danger ms-3 float-right col'><?php echo $locale->_('logout') ?></a>

        </div>

        <form action="" method='get'>
            <div class='row p-4 '>
                <div class="col">
                    <h4><?php echo $locale->_('search') . " " . $locale->_('products') . "..." ?></h4>
                    <input type="text" name="search">
                    <input type="submit" value="search" class="btn btn-dark">
                </div>

                <hr>
            </div>
        </form>
        <table class="table">
            <thead class='bg-dark text-white fw-bold '>
                <tr>
                    <th scope="col"><?php echo $locale->_('name') ?></th>
                    <th scope="col"><?php echo $locale->_('category') ?></th>
                    <th scope="col"><?php echo $locale->_('price') ?></th>
                    <th scope="col"><?php echo $locale->_('stock') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                <?php

                foreach ($products as $idx => $product) {
                ?>

                    <tr>
                        <form action="" method="post">
                            <td>
                                <p><?php echo $product->name ?></p>
                            </td>
                            <td>
                                <p><?php echo $product->category ?></p>
                            </td>
                            <td>
                                <p><?php echo $product->price ?></p>
                            </td>
                            <td>
                                <p><?php echo $product->stock ?></p>
                            </td>
                            <td>
                                <span class="btn btn-primary viewProduct" data-toggle="modal" data-target="#myModal" data-id="<?php echo $product->_id ?>"> view</span>


                            </td>
                        </form>



                    </tr>
                <?php }
                ?>
            </tbody>
        </table>



        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 id='pid' class='float-left'></h3>
                        <button type="button" class="btn btn-danger float-right" data-dismiss="modal">X</button>
                    </div>
                    <div class="modal-body ">
                        <form action='/admin/products/add' method='post'>
                            <div class='productData'></div>

                            <input type="submit" name='btn' class='btn btn-success btn-lg float-right mx-2' value="update">
                            <input type="submit" name='btn' value="delete" class='btn btn-danger btn-lg float-right'>
                        </form>
                    </div>

                </div>

            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="../../../../public/js/products.js"></script>
    </div>
</body>

</html>